### ISSUE TITLE
NRS 11 time metadata management with pbp-json-gen

### ISSUE THREAD

**Issue by ryjombari** [mbari-org/pbp#13]
I met with the NRS hydrophone team to confirm the standard for time metadata management.  The situation is basically as follows: NRS data files are all exactly the same duration (4 hours), which is an attribute shared with our MARS data (10 minutes).  However,  there are real 6-7 second gaps between NRS files, in contrast to the false gaps or overlaps of 1 second cause by jitter in the seconds field of MARS data file names (caused by a glitch in Lucy software).  The bottom line is that we should use the file start times in the NRS flac file names, and not attempt to fill gaps between files by nudging file start times like we do for MARS.  pbp-json-gen currently puts NRS in the same category as MARS and tries to correct jitter.  We want to change the logic to not do this.  It should handle NRS time like it handles SoundTrap time.

**Comment by danellecline** [comment]
Relatively minor change, but I can confirm that the change works as expected. 

Before
```json
{
        "uri": "gs://noaa-passive-bioacoustic/nrs/audio/11/nrs_11_2019-2021/audio/NRS11_20191024_222253.flac",
        "start": "2019-10-24T22:22:13Z",
        "end": "2019-10-25T02:22:13Z",
        "duration_secs": 14400,
        "channels": 1
    }
```

After

```json
    {
        "uri": "gs://noaa-passive-bioacoustic/nrs/audio/11/nrs_11_2019-2021/audio/NRS11_20191024_222253.flac",
        "start": "2019-10-24T22:22:53Z",
        "end": "2019-10-25T02:22:53Z",
        "duration_secs": 14400,
        "channels": 1
    }
```

**Comment by ryjombari** [comment]
Great.  Thank you, Danelle!
