### ISSUE TITLE
pbp-json-gen including extraneous files

### ISSUE THREAD

**Issue by ryjombari** [mbari-org/pbp#15]
Preparing to process NRS11 data for NOAA, I tried the latest pbp-json-gen.  We seem to be back to including extraneous files that contain no data for a day.  For reference, all current NRS11 jsons for 2020 are in Tempbox/ryjo/json-gen_01July2024, and here is a summary:
* 20200101 through 20200313: 8 input files specified (incorrect, extra file ending before processing day)
* 20200314 through 20200817: 7 input files specified (correct, only needed files included)
* 20200818 through 20201231: 8 input files specified (incorrect, extra file ending before processing day)

The problem was caused by using a fixed time buffer to search before the start of a day.  Because file durations vary between recorders, this requires specifying a variable search buffer, and it becomes unreliable.  Carlos and I had solved this with code that selects only:
1) all files that start within the day, and 
2) the one file that starts the day before and ends within the day.

Maybe this change was not merged... or lost when when Danelle modified code to not force NRS data to be gapless?

**Comment by danellecline** [comment]
I will go back and look at the change log. I think there were a few changes made to the logging and to the logic when I was on sick leave.
