### ISSUE TITLE
pbp-json-gen log issue

### ISSUE THREAD

**Issue by ryjombari** [mbari-org/pbp#16]
@carueda

Danelle and I encountered what appears to be a log error from pbp-json-gen applied to MARS data.

Here is the function call:

pbp-json-gen --json-base-dir=json/iclisten \
                                                                           --output-dir=output \
                                                                           --uri=s3://pacific-sound-256khz \
                                                                           --start=20191023 \
                                                                           --end=20191024 \
                                                                           --prefix=MARS \
                                                                           --recorder=ICLISTEN
                                                                           
And here is the error message:

Traceback (most recent call last):
 File "/u/oscapes/pbpnew/virtenv/bin/pbp-json-gen", line 8, in <module>
  sys.exit(main())
 File "/u/oscapes/pbpnew/virtenv/lib/python3.9/site-packages/pbp/main_json_generator.py", line 53, in main
  generator.run()
 File "/u/oscapes/pbpnew/virtenv/lib/python3.9/site-packages/pbp/json_generator/gen_iclisten.py", line 53, in run
  log.info(f"Generating metadata for {self.start} to {self.end}...")
NameError: name 'log' is not defined

What do you think?

**Comment by danellecline** [comment]
Should be fixed with https://github.com/mbari-org/pbp/pull/17
