### ISSUE TITLE
Plot generation issues when running in notebooks

### ISSUE THREAD

**Issue by carueda** [mbari-org/pbp#21]
Just capturing a ticket now, but they have been prevalent for good while already.

I just did a basic testing with a couple of matplotlib specifics steps and the plot is generated without issues for one of the recently generated necdfs.

**Comment by carueda** [comment]
Upon doing various tests, the plotting issues (which again we started noting a long while ago)  arise when PBP and/or PyPAM logic is exercised in the notebook prior to exercising the plotting step.

**Comment by danellecline** [comment]
@carueda It appear the issue is related to  overrides of the plotting in pypam.  This can be resolved by reverting the text.usetex to false and registering the converters


```python
from pbp.plotting import plot_dataset_summary
import sys
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams.update({'text.usetex': False})
pd.plotting.deregister_matplotlib_converters()

sys.path.append('/opt/pbp/workspace')

nc_filename =  'output/NRS11_p20201008.nc'
ds = xr.open_dataset(nc_filename, engine="h5netcdf")
jpeg_filename = nc_filename.replace(".nc", ".jpg")

plot_dataset_summary(
    ds,
    lat_lon_for_solpos=(36.7128, -122.186),
    title='Test',
    ylim=(10, 1000),
    cmlim=(32, 108),
    dpi=300,
    jpeg_filename=jpeg_filename,
    show=True,
) 
print(f"   done: {jpeg_filename}")
```

**Comment by danellecline** [comment]
The engine needs to be h5netcdf as well.

**Comment by carueda** [comment]
still failing

**Comment by carueda** [comment]
weird behavior, but the plotting is again completing upon prior removal of `.nc` (for some reason the HMB generation could not replace it:
```
Unable to save output/NRS11_20201008.nc: [Errno 11] Unable to synchronously create file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
```
