### ISSUE TITLE
Add CITATION.cff file

### ISSUE THREAD

**Issue by carueda** [mbari-org/pbp#23]
Perhaps we are now in good shape for that  @ryjombari , @danellecline ?

It would be an easy task, see https://citation-file-format.github.io/

**Comment by cparcerisas** [comment]
Hi! I think this is necessary for SoundCoop's paper - It will be cited there (deadline this Thursday? 19/09/2024)

**Comment by carueda** [comment]
Thanks @cparcerisas ...

@danellecline @ryjombari there's already a PR https://github.com/mbari-org/pbp/pull/24 onlyu pending your review/approval.

**Comment by carueda** [comment]
@cparcerisas - I'm just noticing the ["references"](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#referencing-other-work) element that is possible in a `CITATION.cff`.  I'm going to add one for PyPAM! .. and then kindly ask you to review.

**Comment by carueda** [comment]
https://github.com/mbari-org/pbp/pull/24 has been merged.  We can always revise things as/when needed.
