### ISSUE TITLE
Merge documentation into this repo?

### ISSUE THREAD

**Issue by carueda** [mbari-org/pbp#49]
We have had a separate repository for the PBP end-user documentation: https://github.com/mbari-org/pbp-doc.

As we plan for the future, wonder if we should consider incorporating the documentation contents into the main PBP repository itself. One reason is to better coordinate code and documentation in the development process. In concrete, any new feature or bug fix should (in general) also include corresponding updated documentation for the end-user.

@danellecline @ryjombari ?

**Comment by danellecline** [comment]
That would be fine with me. Seems like a good idea.

**Comment by ryjombari** [comment]
Ditto.
